name: Build, Test, and Upload Python Package to Test PyPI

on:
  push:
    branches:
      - main
  release:
    types: [created]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install setuptools wheel
          pip install -r requirements.txt

      - name: Build package
        run: |
          python -m build

      - name: Run tests
        run: |
          python -m unittest discover -s tests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-distributions
          path: dist/

  upload-test-pypi:
    runs-on: ubuntu-latest
    needs: build-test
    if: github.event_name == 'push' || github.event_name == 'release'

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: built-distributions
          path: dist/

      - name: Upload package to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: dist/