name: Build and Test Python Package Locally

on:
  push:
    branches:
      - main
  release:
    types: [created]
  # Optionally, add 'workflow_dispatch' to trigger manually
  # workflow_dispatch:

permissions:
  contents: read
  # Adjust permissions as needed

jobs:
  build-test-act:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libhdf5-dev

      - name: Verify HDF5 Installation
        run: |
          ldconfig -p | grep libhdf5

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Run tests
        run: |
          python -m unittest discover
